### ISSUE TITLE
为什么没有广州的节点

### ISSUE THREAD

**Issue by toyo2333** [spiritLHLS/speedtest.net-CN-ID#2]
你的CN的list里没有

'27594' 'Guangzhou, CN'

**Comment by spiritLHLS** [comment]
全部是实际检验过的ID只保证收录是肯定有用的，但不保证100%是全的，官网写的1.6w个节点，我这只爬了1.4w多

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/speedtest.net-CN-ID/blob/main/CN_Telecom.csv

更新有了，估计之前节点在爬虫时出过问题没爬到，现在更新有了，7天爬一次

**Comment by toyo2333** [comment]
> https://github.com/spiritLHLS/speedtest.net-CN-ID/blob/main/CN_Telecom.csv
> 
> 更新有了，估计之前节点在爬虫时出过问题没爬到，现在更新有了，7天爬一次

谢谢你。项目收藏了！

另外，我之所以问这个节点，是因为这个节点速度极差极差，感觉不正常，没办法用来体现正常的测速结果。

你也可以试一试。

**Comment by spiritLHLS** [comment]
三网节点的带宽不是一致大小的，如果你有用过.cn节点的测速就会发现有的节点带宽甚至只有几Mbps大小
