### ISSUE TITLE
关于测速脚本里的一段

### ISSUE THREAD

**Issue by toyo2333** [spiritLHLS/speedtest.net-CN-ID#3]
请教
这段函数是在做什么用呢？

SystemInfo_GetSystemBit() {
    _yellow "checking SystemBit"
    local sysarch="$(uname -m)"
    if [ "${sysarch}" = "unknown" ] || [ "${sysarch}" = "" ]; then
        local sysarch="$(arch)"
    fi
    # 根据架构信息设置系统位数并下载文件,其余 * 包括了 x86_64
    case "${sysarch}" in
        "i386" | "i686")
            LBench_Result_SystemBit_Short="32"
            LBench_Result_SystemBit_Full="i386"
            BESTTRACE_FILE=besttracemac
            ;;
        "armv7l" | "armv8" | "armv8l" | "aarch64")
            LBench_Result_SystemBit_Short="arm"
            LBench_Result_SystemBit_Full="arm"
            BESTTRACE_FILE=besttracearm
            BACKTRACE_FILE=backtrace-linux-arm64.tar.gz
            ;;
        *)
            LBench_Result_SystemBit_Short="64"
            LBench_Result_SystemBit_Full="amd64"
            BESTTRACE_FILE=besttrace
            BACKTRACE_FILE=backtrace-linux-amd64.tar.gz
            ;;
    esac
}

也没有看到backtrace-linux-amd64.tar.gz 或 backtrace-linux-arm64.tar.gz 后续的下载和使用的

**Comment by spiritLHLS** [comment]
本项目来源于 https://github.com/spiritLHLS/ecs 的需求而分出的子项目，所用函数使用的是源项目的函数，可能有部分未使用的函数代码，但不影响本项目的脚本运行。

**Comment by spiritLHLS** [comment]
已更新，已删除对应的无效函数代码
