### ISSUE TITLE
18941 应该不是 CN 节点

### ISSUE THREAD

**Issue by Leao9203** [spiritLHLS/speedtest.net-CN-ID#6]
如题，18941 应该不是 CN 节点，其对应的 Country 应该是 BR。

![image](https://github.com/user-attachments/assets/4fea5c94-c695-4ecc-825a-acfeff3a7484)

**Comment by spiritLHLS** [comment]
speedtest.net 原始数据是这么写的，筛选后的三网测速地址不包含18941
